### PR TITLE
Add binary sensor types

### PR DESCRIPTION
**Pull request by abstractionnl**
Add support for marking sensors as binary ON/OFF sensors.

### CODE REVIEW

**Comment by meatpiHQ** [comment]
@jay-oswald can you please review ```schema.json```

**Comment by jay-oswald** [comment]
Looks good.

Though if were adding `type` I think we need to either make it required, or default it in the `merge.js` code (since 90%+ will be sensor)

**Comment by abstractionnl** [comment]
> Looks good.
> 
> Though if were adding `type` I think we need to either make it required, or default it in the `merge.js` code (since 90%+ will be sensor)

I made this property optional during parse, so it does not need to be required.

**Comment by jay-oswald** [comment]
> > Looks good.
> > Though if were adding `type` I think we need to either make it required, or default it in the `merge.js` code (since 90%+ will be sensor)
> 
> I made this property optional during parse, so it does not need to be required.

Yeah, but that can just make things more confusing it means the default has to be applied in the WiCAN FW, easier to just apply it at this level instead. We can leave it optional for each profile, but then I'd prefer it be defaulted in the `merge.js` file, so WiCAN can rely on it being there.

The C code is low level, and very limited resources, so the more we can do in this JS the less that has to be done in C

**Comment by abstractionnl** [comment]
> > > Looks good.
> > > Though if were adding `type` I think we need to either make it required, or default it in the `merge.js` code (since 90%+ will be sensor)
> > 
> > 
> > I made this property optional during parse, so it does not need to be required.
> 
> Yeah, but that can just make things more confusing it means the default has to be applied in the WiCAN FW, easier to just apply it at this level instead. We can leave it optional for each profile, but then I'd prefer it be defaulted in the `merge.js` file, so WiCAN can rely on it being there.
> 
> The C code is low level, and very limited resources, so the more we can do in this JS the less that has to be done in C

A null check is probably less load for the ESP than having to parse the element and compare it to another string. It also removes some redundant bytes from the json file which should also reduce storage and memory pressure.

**Pull request merged**
