### PR TITLE
[Vehicle Profile] Jaguar I-PACE

### PR DESCRIPTION
**Pull request by seanauff**
Confirmed working on my model year 2019. Based on the work of @dernotte for OVMS3. Currently only the BECM PIDs (except VIN) are supported. More info in the README

### CODE REVIEW

**Comment by dernotte** [comment]
There is a good reading here about latest finding on Ipace canbus... https://www.i-paceforum.com/threads/hv-battery-reports-autel-scanner-tool-can-do-it.8773/#replies

**Comment by seanauff** [comment]
> There is a good reading here about latest finding on Ipace canbus... https://www.i-paceforum.com/threads/hv-battery-reports-autel-scanner-tool-can-do-it.8773/#replies

Great stuff! I had been following that thread a month ago, good to see some progress. I'll try and replicate.

**Review by meatpiHQ — CHANGES_REQUESTED** [review]
Beautiful work! 

Please change the expression `(B4*256)+B5` to `[B4:B5]`

**Comment by seanauff** [comment]
Can do! For odometer I have `B4*65536+B5*256+B6`. How should that be formatted? `[B4:B6]`? My Google fu is not leading me to a reference for the colon operator

**Comment by meatpiHQ** [comment]
> Can do! For odometer I have `B4*65536+B5*256+B6`. How should that be formatted? `[B4:B6]`? My Google fu is not leading me to a reference for the colon operator

Yes that's right, it should be [B4:B6].

**Comment by seanauff** [comment]
OK, all set!

**Comment by meatpiHQ** [comment]
@seanauff one more thing, please remove vehicle_profiles.json from the PR. This file will be automatically generated.

**Comment by seanauff** [comment]
Thanks! I've disabled that action on my fork so future PRs won't have that issue.

**Pull request merged**
