### PR TITLE
Building Vehicle Profiles

### PR DESCRIPTION
**Pull request by jay-oswald**
As discussed on discord, adding a folder for vehicle profiles to make them easy to find/update. Supports as many nested folders as needed for organising them in a way that makes sense, especailly as the number of supported cars grows

The file names don't mean anything to the merge script, it just merges them all together. I have removed the built version for now, so when it is merged in it will get built and we can confirm it is working.

The action will run any time the relevant files are pushed up to the main branch. It currently generates a minified version, as formating it as a pretty version just takes up more space and we already have a folder of pretty versions

### CODE REVIEW

**Comment by jay-oswald** [comment]
Added CODEOWNERS file as well, made @meatpiHQ the owner for everything by default, but then me the owner for this JS used for the vehicle profiles (not the profiles themself). Setting me up as a code owner means I'll get notified if someone makes a PR to update it

**Comment by njh** [comment]
This looks like a great idea! Seems sensible to separate out cars into individual files and then combine them as part of a build process 👍

**Comment by jay-oswald** [comment]
@njh Thanks, I tested the beta with a large single file and was thinking the file will get very out of hand very quickly.

Planning to add a JSON schema at some point soon as well, to validate the configs that people will start to add via PR's, so even if its basically impossible to test peoples PID's and expressions for cars, at least we could make sure the JSON is structured correctly.

@meatpiHQ just realised I would need to be added as a collaborator for codeowners to work properly, happy to be added and manage the build/validation process for these json files, or can just revert the codeowners addition

**Review by meatpiHQ — APPROVED** [review]

**Comment by jay-oswald** [comment]
Hey @cr0i consistently would be good, but I just copied configs that already existed and people were using. So changing them would have changed things. The other thing is its not like people are swapping between various cars regularly.

If you think it is better to break backwards compatibility for consistantly then feel free to put in a PR with the change and make your reasoning

**Pull request merged**
